### PR TITLE
Add flight search, retire flight itinerary

### PR DESCRIPTION
**Pull request by randunel**
This PR adds `/search`, `/selectedOutboundFlight` and `/selectedInboundFlight` and removes `/itinerary`.

There is currently no `outboundFlights` or `inboundFlights` output, as we do not have the tools to output these and significant development would be require to get these. Off the top of my head:

- date parser with dates and times in different keys
- `airport name` (English or LocalLanguage) to `airport code + country code` translation
- various JSON tools only available in UDF

### CODE REVIEW

**Comment by nicck** [comment]
any reasons why it's `DateAirport`, `DatePlace` but not `DateAirport`, `DateTimeAirport`?

**Comment by randunel** [comment]
- `DateAirport` is new (added with this PR) and it contains `date` and `airport`.
- `DatePlace` is old (added a year ago) and it contains `date`, `time` and `airport`. I haven't renamed it for maintenance/confusion reasons, but it would make more sense to be named `DateTimeAirport`

@nicck, do you think corrections of old keys should be included in this change? These corrections should also correct `PriceConsent` (which is just object-with-price) and a review of all inconsistent names (e.g. why `Place` and not `Airport`?)

**Comment by muzafarova** [comment]
That's quite optimistic that the max age is 200 :D 

I have a silly question (maybe I just can't figure the presentation out) 
image
What happened to `cabinClass`? I see it in `required` list, but in `properties` schema there is only a `description`, no `cabinClass` key.. looks weird

**Comment by randunel** [comment]
The generated json looks weird, my changes are here: https://github.com/universalbasket/protocol/pull/23/files#diff-96a057b8474f17b4e720491ec38940d4

**Comment by nicck** [comment]
Introducing `DateAirport` creates confusion with `DatePlace`, so it makes sense to fix it now, but not fix the `PriceConsent` to reduce amount of changes and b/c it has nothing to do with search/itinerary.

**Comment by randunel** [comment]
Renamed `DatePlace` to `DateTimeAirport`, as I couldn't find a better name :/

**Comment by nicck** [comment]
As I understand we need to put original (with datTime) itinerery back to not break existing scripts and clients.

**Pull request merged**
